`day-02-installation-and-setup/commands.sh`

```bash
#!/bin/bash

# ==========================================================
# Day 2 - Install HashiCorp Vault Locally
# Vault Zero to Hero Series
# ==========================================================

# NOTE:
# This file contains commands used for Day 2.
# Some commands are OS-specific.
# Use the section that matches your operating system.

# ==========================================================
# 1. Verify Vault Installation
# ==========================================================

vault --version


# ==========================================================
# 2. Linux Installation Example
# ==========================================================

# Replace <version> with the Vault version you downloaded.
# Example version format: 1.19.0, 1.20.0, etc.

# wget https://releases.hashicorp.com/vault/<version>/vault_<version>_linux_amd64.zip
# unzip vault_<version>_linux_amd64.zip
# sudo mv vault /usr/local/bin/
# vault --version

# Example:
# wget https://releases.hashicorp.com/vault/1.19.0/vault_1.19.0_linux_amd64.zip
# unzip vault_1.19.0_linux_amd64.zip
# sudo mv vault /usr/local/bin/
# vault --version


# ==========================================================
# 3. macOS Installation Example
# ==========================================================

# brew tap hashicorp/tap
# brew install hashicorp/tap/vault
# vault --version


# ==========================================================
# 4. Windows PowerShell Installation Verification
# ==========================================================

# After downloading and extracting Vault:
# 1. Add Vault folder path to Environment Variables.
# 2. Open a new PowerShell window.
# 3. Run:
#
# vault --version


# ==========================================================
# 5. Start Vault in Dev Mode
# ==========================================================

# This starts Vault locally in development mode.
# Keep this terminal running.
# Do not use Dev Mode in production.

vault server -dev


# ==========================================================
# 6. Set Vault Environment Variables - Linux/macOS
# ==========================================================

# Open a new terminal before running these commands.
# Copy the Root Token from the terminal where Vault is running.

export VAULT_ADDR="http://127.0.0.1:8200"
export VAULT_TOKEN="<paste-root-token-here>"


# ==========================================================
# 7. Set Vault Environment Variables - Windows PowerShell
# ==========================================================

# Use these commands in PowerShell:
#
# $env:VAULT_ADDR="http://127.0.0.1:8200"
# $env:VAULT_TOKEN="<paste-root-token-here>"


# ==========================================================
# 8. Set Vault Environment Variables - Windows Command Prompt
# ==========================================================

# Use these commands in Command Prompt:
#
# set VAULT_ADDR=http://127.0.0.1:8200
# set VAULT_TOKEN=<paste-root-token-here>


# ==========================================================
# 9. Check Vault Status
# ==========================================================

vault status


# ==========================================================
# 10. Access Vault UI
# ==========================================================

# Open this URL in your browser:
#
# http://127.0.0.1:8200
#
# Login using the Root Token generated by:
#
# vault server -dev


# ==========================================================
# 11. Stop Vault Dev Server
# ==========================================================

# Go to the terminal where Vault server is running.
# Press CTRL + C.
#
# Since Dev Mode uses in-memory storage,
# data will be lost after stopping the server.

# ==========================================================
# End of Day 2 Commands
# ==========================================================